<?php

$template_array = array(
    'post_title' => 'Video Bg Inline',
    'post_content' => '',
    'metadata' => array(
        '_chatflow_type' => 'bot+livechat'
    ),
    'questions' => array(
        array(
            'id' => '10000000',
            'next_question_id' => '1630',
            'post_title' => 'Welcome screen',
            'post_content' => 'Hey there, this is your next <strong>marketing agency</strong> speaking',
            'type' => 'welcome',
            'image' => 'https://dapdemo.membershipsitechallenge.com/wp-content/uploads/2023/10/giphy-downsized.gif',
        ),
        array(
            'id' => '10000001',
            'next_question_id' => '1631',
            'post_title' => 'Your company is the guy over there',
            'post_content' => 'Your company is the guy over there 👆 and we\'re the <strong>string pullers</strong>!',
            'type' => 'single',
            'quick_reply_buttons' => array(
                                        array(
                                            'id' => 'id-8097942475641745',
                                            'title' => 'You got my attention',
                                            'image' => 'https://dapdemo.membershipsitechallenge.com/wp-content/plugins/listbuildingbot/admin/images/no-image.png',
                                            'tags' => array(),
                                            'tag' => '',
                                            'outcome' => '',
                                            'answer_action' => '',
                                            'url' => '',
                                            'point' => 0,
                                            'repeat_ques' => '',
                                            'map' => '1631',
                                        ),
                                ),
        ),
        array(
            'id' => '10000002',
            'next_question_id' => '1634',
            'post_title' => 'What would you like to know?',
            'post_content' => 'What would you like to know?',
            'type' => 'single',
            'quick_reply_buttons' => array(
                                        array(
                                            'id' => 'id-1090325918698039',
                                            'title' => 'Contact us',
                                            'image' => 'https://dapdemo.membershipsitechallenge.com/wp-content/plugins/listbuildingbot/admin/images/no-image.png',
                                            'tags' => array(),
                                            'tag' => '',
                                            'outcome' => '',
                                            'answer_action' => '',
                                            'url' => '',
                                            'point' => 0,
                                            'repeat_ques' => '',
                                            'map' => '1634',
                                        ),
                                        array(
                                            'id' => 'id-5205854765246365',
                                            'title' => 'Services',
                                            'image' => 'https://dapdemo.membershipsitechallenge.com/wp-content/plugins/listbuildingbot/admin/images/no-image.png',
                                            'tags' => array(),
                                            'tag' => '',
                                            'outcome' => '',
                                            'answer_action' => '',
                                            'url' => '',
                                            'point' => 0,
                                            'repeat_ques' => '',
                                            'map' => '1654',
                                        ),
                                        
                                ),


        ),
        array(
            'id' => '10000003',
            'next_question_id' => '1637',
            'post_title' => 'What&#8217;s your name?',
            'post_content' => 'What\'s your <strong>name</strong>?',
            'type' => 'name',
            'funnel_placeholder' => 'Type your name here..',
            'custom_placeholder' => '1',
        ),
        array(
            'id' => '10000004',
            'next_question_id' => '1638',
            'post_title' => 'What&#8217;s your company name?',
            'post_content' => 'Great to meet you <strong>%NAME%</strong>!<br />What\'s your <strong>company name</strong>?',
            'type' => 'text',
            'funnel_placeholder' => 'Type here..',
        ),
        array(
            'id' => '10000005',
            'next_question_id' => '1639',
            'post_title' => 'And your <strong>work email</strong>? ',
            'post_content' => 'And your <strong>work email</strong>?',
            'type' => 'email',
            'funnel_placeholder' => 'Type your email here..',
        ),
        array(
            'id' => '10000006',
            'next_question_id' => '1641',
            'post_title' => 'Services are you interested in',
            'post_content' => 'Which of our <strong>services</strong> are you interested in?',
            'type' => 'single',
            'quick_reply_buttons' => array(
                                        array(
                                            'id' => 'id-5858129065860365',
                                            'title' => 'SEO',
                                            'image' => 'https://dapdemo.membershipsitechallenge.com/wp-content/plugins/listbuildingbot/admin/images/no-image.png',
                                            'tags' => array(),
                                            'tag' => '',
                                            'outcome' => '',
                                            'answer_action' => '',
                                            'url' => '',
                                            'point' => 0,
                                            'repeat_ques' => '',
                                            'map' => '1641',
                                        ),
                                        array(
                                            'id' => 'id-6533894361873295',
                                            'title' => 'Branding',
                                            'image' => 'https://dapdemo.membershipsitechallenge.com/wp-content/plugins/listbuildingbot/admin/images/no-image.png',
                                            'tags' => array(),
                                            'tag' => '',
                                            'outcome' => '',
                                            'answer_action' => '',
                                            'url' => '',
                                            'point' => 0,
                                            'repeat_ques' => '',
                                            'map' => '1641',
                                        ),
                                        array(
                                            'id' => 'id-407478113311087',
                                            'title' => 'Google Ads',
                                            'image' => 'https://dapdemo.membershipsitechallenge.com/wp-content/plugins/listbuildingbot/admin/images/no-image.png',
                                            'tags' => array(),
                                            'tag' => '',
                                            'outcome' => '',
                                            'answer_action' => '',
                                            'url' => '',
                                            'point' => 0,
                                            'repeat_ques' => '',
                                            'map' => '1641',
                                        ),
                                        
                                ),


        ),
        array(
            'id' => '10000007',
            'next_question_id' => '1642',
            'post_title' => 'Monthly budget',
            'post_content' => 'What is your rough <strong>monthly budget</strong>?  ',
            'type' => 'text',
            'funnel_placeholder' => 'Type here..',
        ),
        array(
            'id' => '10000008',
            'next_question_id' => '1644',
            'post_title' => 'Tell us a little bit about what',
            'post_content' => 'Tell us a little bit about what are you are looking for...',
            'type' => 'text',
            'funnel_placeholder' => 'Type here..',
        ),
        array(
            'id' => '10000009',
            'next_question_id' => '1654',
            'post_title' => 'All set, we will get back  ',
            'post_content' => 'All set, we will get back to you ASAP!',
            'type' => 'single',
            'quick_reply_buttons' => array(
                                        array(
                                            'id' => 'id-551657572877813',
                                            'title' => 'Main Menu',
                                            'image' => 'https://dapdemo.membershipsitechallenge.com/wp-content/plugins/listbuildingbot/admin/images/no-image.png',
                                            'tags' => array(),
                                            'tag' => '',
                                            'outcome' => '',
                                            'answer_action' => '',
                                            'url' => '',
                                            'point' => 0,
                                            'repeat_ques' => '1631',
                                            'map' => '',
                                        ),
                                        
                                ),


        ),
        array(
            'id' => '10000010',
            'next_question_id' => '1655',
            'post_title' => 'We specialize',
            'post_content' => 'We specialize in SEO, branding, and Google ads. Select one to learn more:',
            'type' => 'single',
            'quick_reply_buttons' => array(
                                        array(
                                            'id' => 'id-4080529832548427',
                                            'title' => 'SEO',
                                            'image' => 'https://dapdemo.membershipsitechallenge.com/wp-content/plugins/listbuildingbot/admin/images/no-image.png',
                                            'tags' => array(),
                                            'tag' => '',
                                            'outcome' => '',
                                            'answer_action' => '',
                                            'url' => '',
                                            'point' => 0,
                                            'repeat_ques' => '',
                                            'map' => '1655',
                                        ),array(
                                            'id' => 'id-8472500882776045',
                                            'title' => 'Branding',
                                            'image' => 'https://dapdemo.membershipsitechallenge.com/wp-content/plugins/listbuildingbot/admin/images/no-image.png',
                                            'tags' => array(),
                                            'tag' => '',
                                            'outcome' => '',
                                            'answer_action' => '',
                                            'url' => '',
                                            'point' => 0,
                                            'repeat_ques' => '',
                                            'map' => '1656',
                                        ),array(
                                            'id' => 'id-3698897774113021',
                                            'title' => 'Google ads',
                                            'image' => 'https://dapdemo.membershipsitechallenge.com/wp-content/plugins/listbuildingbot/admin/images/no-image.png',
                                            'tags' => array(),
                                            'tag' => '',
                                            'outcome' => '',
                                            'answer_action' => '',
                                            'url' => '',
                                            'point' => 0,
                                            'repeat_ques' => '',
                                            'map' => '1657',
                                        ),
                                        
                                ),


        ),
        array(
            'id' => '10000011',
            'next_question_id' => '1656',
            'post_title' => 'More than 80% of our clients rank on the first page',
            'post_content' => 'More than 80% of our clients rank on the first page for their niches. We do so through tailored content and backlinking outreach',
            'type' => 'single',
            'quick_reply_buttons' => array(
                                        array(
                                            'id' => 'id-1604901642119317',
                                            'title' => 'Contact us',
                                            'image' => 'https://dapdemo.membershipsitechallenge.com/wp-content/plugins/listbuildingbot/admin/images/no-image.png',
                                            'tags' => array(),
                                            'tag' => '',
                                            'outcome' => '',
                                            'answer_action' => '',
                                            'url' => '',
                                            'point' => 0,
                                            'repeat_ques' => '',
                                            'map' => '1634',
                                        ),array(
                                            'id' => 'id-8627834994044663',
                                            'title' => 'Back to menu',
                                            'image' => 'https://dapdemo.membershipsitechallenge.com/wp-content/plugins/listbuildingbot/admin/images/no-image.png',
                                            'tags' => array(),
                                            'tag' => '',
                                            'outcome' => '',
                                            'answer_action' => '',
                                            'url' => '',
                                            'point' => 0,
                                            'repeat_ques' => '1631',
                                            'map' => '',
                                        ),
                                        
                                ),


        ),
        array(
            'id' => '10000012',
            'next_question_id' => '1657',
            'post_title' => 'We work with many household brands',
            'post_content' => 'We work with many household brands to connect with their Gen Z audience.',
            'type' => 'single',
            'quick_reply_buttons' => array(
                                        array(
                                            'id' => 'id-4389894542748457',
                                            'title' => 'Contact us',
                                            'image' => 'https://dapdemo.membershipsitechallenge.com/wp-content/plugins/listbuildingbot/admin/images/no-image.png',
                                            'tags' => array(),
                                            'tag' => '',
                                            'outcome' => '',
                                            'answer_action' => '',
                                            'url' => '',
                                            'point' => 0,
                                            'repeat_ques' => '',
                                            'map' => '1634',
                                        ),array(
                                            'id' => 'id-8393631262868953',
                                            'title' => 'Back to menu',
                                            'image' => 'https://dapdemo.membershipsitechallenge.com/wp-content/plugins/listbuildingbot/admin/images/no-image.png',
                                            'tags' => array(),
                                            'tag' => '',
                                            'outcome' => '',
                                            'answer_action' => '',
                                            'url' => '',
                                            'point' => 0,
                                            'repeat_ques' => '1631',
                                            'map' => '',
                                        ),
                                        
                                ),


        ),
        array(
            'id' => '10000013',
            'next_question_id' => '',
            'post_title' => 'We only focus on Google ads because we believe',
            'post_content' => "We only focus on Google ads because we believe it is the highest ROI paid channel.<br /><br />On avereage, we reduce our clients' CPC by 40%!",
            'type' => 'single',
            'quick_reply_buttons' => array(
                                        array(
                                            'id' => 'id-3411932803978047',
                                            'title' => 'Contact us',
                                            'image' => 'https://dapdemo.membershipsitechallenge.com/wp-content/plugins/listbuildingbot/admin/images/no-image.png',
                                            'tags' => array(),
                                            'tag' => '',
                                            'outcome' => '',
                                            'answer_action' => '',
                                            'url' => '',
                                            'point' => 0,
                                            'repeat_ques' => '',
                                            'map' => '1634',
                                        ),array(
                                            'id' => 'id-5180523571540775',
                                            'title' => 'Back to menu',
                                            'image' => 'https://dapdemo.membershipsitechallenge.com/wp-content/plugins/listbuildingbot/admin/images/no-image.png',
                                            'tags' => array(),
                                            'tag' => '',
                                            'outcome' => '',
                                            'answer_action' => '',
                                            'url' => '',
                                            'point' => 0,
                                            'repeat_ques' => '1631',
                                            'map' => '',
                                        ),
                                        
                                ),


        ),
    ),
    'oldQuestionId' => array(
        '1628' => 'NEW_ID_1',
        '1630' => 'NEW_ID_2',
        '1631' => 'NEW_ID_3',
        '1634' => 'NEW_ID_4',
        '1637' => 'NEW_ID_5',
        '1638' => 'NEW_ID_6',
        '1639' => 'NEW_ID_7',
        '1641' => 'NEW_ID_8',
        '1642' => 'NEW_ID_9',
        '1644' => 'NEW_ID_10',
        '1654' => 'NEW_ID_11',
        '1655' => 'NEW_ID_12',
        '1656' => 'NEW_ID_13',
        '1657' => 'NEW_ID_14',
    ),
    '_questions_drawflow' => '{"drawflow":{"Home":{"data":{"1":{"id":1,"name":"multiple","data":{"question_id":1628},"class":"multiple node-question-1628 node-question-1628 node-question-1628 node-question-1628 node-question-1628 node-question-1628","html":"","typenode":false,"inputs":[],"outputs":{"output_1":{"connections":[{"node":"2","output":"input_1"}]}},"pos_x":35,"pos_y":151},"2":{"id":2,"name":"multiple","data":{"question_id":1630},"class":"multiple node-question-1630 node-question-1630 node-question-1630 node-question-1630","html":"","typenode":false,"inputs":{"input_1":{"connections":[{"node":"1","input":"output_1"}]}},"outputs":{"output_1":{"connections":[{"node":"3","output":"input_1"}]}},"pos_x":385,"pos_y":100},"3":{"id":3,"name":"multiple","data":{"question_id":1631},"class":"multiple node-question-1631 node-question-1631 node-question-1631 node-question-1631","html":"","typenode":false,"inputs":{"input_1":{"connections":[{"node":"2","input":"output_1"}]}},"outputs":{"output_1":{"connections":[{"node":"4","output":"input_1"}]},"output_2":{"connections":[{"node":"13","output":"input_1"}]}},"pos_x":661,"pos_y":114},"4":{"id":4,"name":"multiple","data":{"question_id":1634},"class":"multiple node-question-1634 node-question-1634 node-question-1634 node-question-1634","html":"","typenode":false,"inputs":{"input_1":{"connections":[{"node":"3","input":"output_1"},{"node":"14","input":"output_1"},{"node":"15","input":"output_1"},{"node":"16","input":"output_1"}]}},"outputs":{"output_1":{"connections":[{"node":"6","output":"input_1"}]}},"pos_x":1011,"pos_y":97.5714285714285693984493263997137546539306640625},"6":{"id":6,"name":"multiple","data":{"question_id":1637},"class":"multiple node-question-1637 node-question-1637 node-question-1637 node-question-1637","html":"","typenode":false,"inputs":{"input_1":{"connections":[{"node":"4","input":"output_1"}]}},"outputs":{"output_1":{"connections":[{"node":"7","output":"input_1"}]}},"pos_x":1361,"pos_y":100},"7":{"id":7,"name":"multiple","data":{"question_id":1638},"class":"multiple node-question-1638 node-question-1638 node-question-1638 node-question-1638","html":"","typenode":false,"inputs":{"input_1":{"connections":[{"node":"6","input":"output_1"}]}},"outputs":{"output_1":{"connections":[{"node":"8","output":"input_1"}]}},"pos_x":1711,"pos_y":100},"8":{"id":8,"name":"multiple","data":{"question_id":1639},"class":"multiple node-question-1639 node-question-1639 node-question-1639 node-question-1639","html":"","typenode":false,"inputs":{"input_1":{"connections":[{"node":"7","input":"output_1"}]}},"outputs":{"output_1":{"connections":[{"node":"9","output":"input_1"}]},"output_2":{"connections":[{"node":"9","output":"input_1"}]},"output_3":{"connections":[{"node":"9","output":"input_1"}]}},"pos_x":2061,"pos_y":100},"9":{"id":9,"name":"multiple","data":{"question_id":1641},"class":"multiple node-question-1641 node-question-1641 node-question-1641 node-question-1641","html":"","typenode":false,"inputs":{"input_1":{"connections":[{"node":"8","input":"output_1"},{"node":"8","input":"output_2"},{"node":"8","input":"output_3"}]}},"outputs":{"output_1":{"connections":[{"node":"10","output":"input_1"}]}},"pos_x":2403,"pos_y":187},"10":{"id":10,"name":"multiple","data":{"question_id":1642},"class":"multiple node-question-1642 node-question-1642 node-question-1642 node-question-1642","html":"","typenode":false,"inputs":{"input_1":{"connections":[{"node":"9","input":"output_1"}]}},"outputs":{"output_1":{"connections":[{"node":"12","output":"input_1"}]}},"pos_x":2698,"pos_y":185},"12":{"id":12,"name":"multiple","data":{"question_id":1644},"class":"multiple node-question-1644 node-question-1644 node-question-1644 node-question-1644","html":"","typenode":false,"inputs":{"input_1":{"connections":[{"node":"10","input":"output_1"}]}},"outputs":{"output_1":{"connections":[]}},"pos_x":3052,"pos_y":104},"13":{"id":13,"name":"multiple","data":{"question_id":1654},"class":"multiple node-question-1654","html":"","typenode":false,"inputs":{"input_1":{"connections":[{"node":"3","input":"output_2"}]}},"outputs":{"output_1":{"connections":[{"node":"14","output":"input_1"}]},"output_2":{"connections":[{"node":"15","output":"input_1"}]},"output_3":{"connections":[{"node":"16","output":"input_1"}]}},"pos_x":635,"pos_y":517},"14":{"id":14,"name":"multiple","data":{"question_id":1655},"class":"multiple node-question-1655","html":"","typenode":false,"inputs":{"input_1":{"connections":[{"node":"13","input":"output_1"}]}},"outputs":{"output_1":{"connections":[{"node":"4","output":"input_1"}]},"output_2":{"connections":[]}},"pos_x":988,"pos_y":288},"15":{"id":15,"name":"multiple","data":{"question_id":1656},"class":"multiple node-question-1656","html":"","typenode":false,"inputs":{"input_1":{"connections":[{"node":"13","input":"output_2"}]}},"outputs":{"output_1":{"connections":[{"node":"4","output":"input_1"}]},"output_2":{"connections":[]}},"pos_x":998,"pos_y":676},"16":{"id":16,"name":"multiple","data":{"question_id":1657},"class":"multiple node-question-1657","html":"","typenode":false,"inputs":{"input_1":{"connections":[{"node":"13","input":"output_3"}]}},"outputs":{"output_1":{"connections":[{"node":"4","output":"input_1"}]},"output_2":{"connections":[]}},"pos_x":986,"pos_y":1014}}}}}',
    'title_name' => 'Video Bg Inline',
    'lbb_admin_name' => 'Admin',
    'lbb_chatbot_description' => 'This is description about ADMIN',
    'livechat_status' => 'no',
    'welcome_message' => 'Welcome to live chat!',
    'live_chat_idle_time_enable' => 'yes',
    'how_to_show' => 'inline',
    'minimized_type' => 'icon',
    'video_text' => 'Talk to live agent',
    'when_to_show' => 'visitor_visit',
    'page_scroll_value' => '10',
    'who_should_see' => 'all_visitor',
    'set_timeout' => '60',
    'email_capture' => 'just_email',
    'lbb_notify_chat' => 'no',
    'chatbot_style_global_status' => '0',
    'lbb_container_width' => '700',
    'lbb_common_font_family' => 'Open Sans',
    'lbb_heading_background_color' => '#2000f0',
    'lbb_image_upload' => 'https://dapdemo.membershipsitechallenge.com/wp-content/plugins/listbuildingbot/admin/images/avatar.png',
    'heading_style_global_status' => '0',
    'lbb_heading_font_size' => '20',
    'lbb_heading_font_weight' => '600',
    'lbb_heading_text_color' => '#fff',
    'lbb_sub_heading_font_size' => '15',
    'lbb_sub_heading_font_weight' => '600',
    'lbb_sub_heading_text_color' => '#000000',
    'question_style_global_status' => '0',
    'lbb_question_font_size' => '16',
    'lbb_question_font_weight' => '400',
    'lbb_question_text_color' => '#2f324a',
    'lbb_question_background_color' => '#ffffff',
    'answer_style_global_status' => '0',
    'lbb_ans_bg_color' => '#0066ff',
    'lbb_ans_border_color' => '#0066ff',
    'lbb_ans_text_color' => '#ffffff',
    'lbb_ans_border_radius' => '5',
    'lbb_ans_font_size' => '16',
    'lbb_ans_font_weight' => '400',
    'alignment_style_global_status' => '0',
    'chat_alignment' => 'right',
    'lbb_right_spacing' => '20',
    'lbb_left_spacing' => '20',
    'lbb_bottom_spacing' => '20',
    'expanded_style_global_status' => '0',
    'backgroun_style_global_status' => '0',
    'lbb_style_chatbot_background' => 'video',
    'lbb_chat_background_color' => '#fff',
    'lbb_chat_background_image' => '',
    'lbb_chat_background_video' => 'https://dapdemo.membershipsitechallenge.com/wp-content/uploads/2023/10/video_4.mp4',
    'automation_triggered' => 'after_email',
    'lbb_container_padding' => '15',
    'lbb_question_input_border_color' => '#0066ff',
)
?>