<?php

$template_array = array(
    'post_title' => 'New Prebuilt',
    'post_content' => '',
    'metadata' => array(
        '_chatflow_type' => 'bot+livechat'
    ),
    'questions' => array(
        array(
            'id' => '10000000',
            'next_question_id' => '1392',
            'post_title' => 'Welcome screen',
            'post_content' => 'Join us for our upcoming webinars <br><strong>How to invest $10000 today </strong></br>📅 April 1st, 8-9PM EST',
            'type' => 'welcome',
            'image' => 'http://php8.membershipsitechallenge.com/wp-content/uploads/2023/10/giphy.webp',
        ),
        array(
            'id' => '10000001',
            'next_question_id' => '1397',
            'post_title' => 'Choose an option',
            'post_content' => 'Choose an option',
            'type' => 'single',
            'quick_reply_buttons' => array(
                                        array(
                                            'id' => 'id-2263812802918839',
                                            'title' => 'Tell me more',
                                            'image' => 'https://dapdemo.membershipsitechallenge.com/wp-content/plugins/listbuildingbot/admin/images/no-image.png',
                                            'tags' => array(),
                                            'tag' => '',
                                            'outcome' => '',
                                            'answer_action' => '',
                                            'url' => '',
                                            'point' => 0,
                                            'repeat_ques' => '',
                                            'map' => '1397',
                                        ),array(
                                            'id' => 'id-8311661806513769',
                                            'title' => 'Sign me up!',
                                            'image' => 'https://dapdemo.membershipsitechallenge.com/wp-content/plugins/listbuildingbot/admin/images/no-image.png',
                                            'tags' => array(),
                                            'tag' => '',
                                            'outcome' => '',
                                            'answer_action' => '',
                                            'url' => '',
                                            'point' => 0,
                                            'repeat_ques' => '',
                                            'map' => '1399',
                                        ),
                                ),
        ),
        array(
            'id' => '10000002',
            'next_question_id' => '1399',
            'post_title' => 'Sign me up!',
            'post_content' => 'In this webinar, our investment expert Amanda May will tell you how to invest your money in this fast-moving market.<br>She will talk about ETF, crypto, NFT, real estate, and other ways to grow your wealth.',
            'type' => 'single',
            'quick_reply_buttons' => array(
                                        array(
                                            'id' => 'id-5888368975913949',
                                            'title' => 'Sign me up!',
                                            'image' => 'https://dapdemo.membershipsitechallenge.com/wp-content/plugins/listbuildingbot/admin/images/no-image.png',
                                            'tags' => array(),
                                            'tag' => '',
                                            'outcome' => '',
                                            'answer_action' => '',
                                            'url' => '',
                                            'point' => 0,
                                            'repeat_ques' => '',
                                            'map' => '1399',
                                        ),
                                ),
        ),
        array(
            'id' => '10000003',
            'next_question_id' => '1401',
            'post_title' => 'Awesome! Let me get your details',
            'post_content' => 'Awesome! Let me get your details What\'s your name?',
            'type' => 'name',
            'funnel_placeholder' => 'Type your name here..',
            'custom_placeholder' => '1',
        ),
        array(
            'id' => '10000005',
            'next_question_id' => '1402',
            'post_title' => 'And your email?',
            'post_content' => 'And your email?',
            'type' => 'email',
            'funnel_placeholder' => 'Type your email here..',
        ),
        array(
            'id' => '10000006',
            'next_question_id' => '1403',
            'post_title' => 'How did you hear about us?',
            'post_content' => 'How did you hear about us?',
            'type' => 'single',
            'quick_reply_buttons' => array(
                                        array(
                                            'id' => 'id-5516950638728697',
                                            'title' => 'Facebook',
                                            'image' => 'https://dapdemo.membershipsitechallenge.com/wp-content/plugins/listbuildingbot/admin/images/no-image.png',
                                            'tags' => array(),
                                            'tag' => '',
                                            'outcome' => '',
                                            'answer_action' => '',
                                            'url' => '',
                                            'point' => 0,
                                            'repeat_ques' => '',
                                            'map' => '1403',
                                        ),
                                        array(
                                            'id' => 'id-6417721070752145',
                                            'title' => 'Google',
                                            'image' => 'https://dapdemo.membershipsitechallenge.com/wp-content/plugins/listbuildingbot/admin/images/no-image.png',
                                            'tags' => array(),
                                            'tag' => '',
                                            'outcome' => '',
                                            'answer_action' => '',
                                            'url' => '',
                                            'point' => 0,
                                            'repeat_ques' => '',
                                            'map' => '1403',
                                        ),array(
                                            'id' => 'id-3063277767389325',
                                            'title' => 'Meetup.com',
                                            'image' => 'https://dapdemo.membershipsitechallenge.com/wp-content/plugins/listbuildingbot/admin/images/no-image.png',
                                            'tags' => array(),
                                            'tag' => '',
                                            'outcome' => '',
                                            'answer_action' => '',
                                            'url' => '',
                                            'point' => 0,
                                            'repeat_ques' => '',
                                            'map' => '1403',
                                        ),
                                        array(
                                            'id' => 'id-8228343661274197',
                                            'title' => 'Word of Mouth',
                                            'image' => 'https://dapdemo.membershipsitechallenge.com/wp-content/plugins/listbuildingbot/admin/images/no-image.png',
                                            'tags' => array(),
                                            'tag' => '',
                                            'outcome' => '',
                                            'answer_action' => '',
                                            'url' => '',
                                            'point' => 0,
                                            'repeat_ques' => '',
                                            'map' => '1403',
                                        ),array(
                                            'id' => 'id-1403953242884613',
                                            'title' => 'Other',
                                            'image' => 'https://dapdemo.membershipsitechallenge.com/wp-content/plugins/listbuildingbot/admin/images/no-image.png',
                                            'tags' => array(),
                                            'tag' => '',
                                            'outcome' => '',
                                            'answer_action' => '',
                                            'url' => '',
                                            'point' => 0,
                                            'repeat_ques' => '',
                                            'map' => '1403',
                                        ),
                                        
                                ),


        ),
        array(
            'id' => '10000009',
            'next_question_id' => '1406',
            'post_title' => 'Would you like to join our mailing list to be infromed about our future events?',
            'post_content' => 'Would you like to join our mailing list to be infromed about our future events?',
            'type' => 'single',
            'quick_reply_buttons' => array(
                                        array(
                                            'id' => 'id-175935911428529',
                                            'title' => 'Yes, keep me posted!',
                                            'image' => 'https://dapdemo.membershipsitechallenge.com/wp-content/plugins/listbuildingbot/admin/images/no-image.png',
                                            'tags' => array(),
                                            'tag' => '',
                                            'outcome' => '',
                                            'answer_action' => '',
                                            'url' => '',
                                            'point' => 0,
                                            'repeat_ques' => '',
                                            'map' => '1406',
                                        ),array(
                                            'id' => 'id-1192436283267001',
                                            'title' => 'Nope',
                                            'image' => 'https://dapdemo.membershipsitechallenge.com/wp-content/plugins/listbuildingbot/admin/images/no-image.png',
                                            'tags' => array(),
                                            'tag' => '',
                                            'outcome' => '',
                                            'answer_action' => '',
                                            'url' => '',
                                            'point' => 0,
                                            'repeat_ques' => '',
                                            'map' => '1406',
                                        ),
                                        
                                ),


        ),
        array(
            'id' => '10000010',
            'next_question_id' => '',
            'post_title' => 'All set, see you there!',
            'post_content' => 'All set, see you there!',
            'type' => 'single',
            'quick_reply_buttons' => array(
                                        array(
                                            'id' => 'id-7503103752837169',
                                            'title' => 'Start Over',
                                            'image' => 'https://dapdemo.membershipsitechallenge.com/wp-content/plugins/listbuildingbot/admin/images/no-image.png',
                                            'tags' => array(),
                                            'tag' => '',
                                            'outcome' => '',
                                            'answer_action' => '',
                                            'url' => '',
                                            'point' => 0,
                                            'repeat_ques' => '',
                                            'map' => '',
                                        ),
                                        
                                ),


        ),
    ),
    'oldQuestionId' => array(
        '1390' => 'NEW_ID_1',
        '1392' => 'NEW_ID_2',
        '1397' => 'NEW_ID_3',
        '1399' => 'NEW_ID_4',
        '1401' => 'NEW_ID_5',
        '1402' => 'NEW_ID_6',
        '1403' => 'NEW_ID_7',
        '1406' => 'NEW_ID_8',
    ),
    '_questions_drawflow' => '{"drawflow":{"Home":{"data":{"1":{"id":1,"name":"multiple","data":{"question_id":1390},"class":"multiple node-question-1390 node-question-1390 node-question-1390 node-question-1390 node-question-1390 node-question-1390 node-question-1390 node-question-1390 node-question-1390 node-question-1390 node-question-1390","html":"","typenode":false,"inputs":[],"outputs":{"output_1":{"connections":[{"node":"3","output":"input_1"}]}},"pos_x":-119,"pos_y":186},"3":{"id":3,"name":"multiple","data":{"question_id":1392},"class":"multiple node-question-1392 node-question-1392 node-question-1392 node-question-1392 node-question-1392 node-question-1392 node-question-1392 node-question-1392 node-question-1392","html":"","typenode":false,"inputs":{"input_1":{"connections":[{"node":"1","input":"output_1"}]}},"outputs":{"output_1":{"connections":[{"node":"7","output":"input_1"}]},"output_2":{"connections":[{"node":"9","output":"input_1"}]}},"pos_x":127,"pos_y":176},"7":{"id":7,"name":"multiple","data":{"question_id":1397},"class":"multiple node-question-1397 node-question-1397 node-question-1397 node-question-1397 node-question-1397 node-question-1397 node-question-1397 node-question-1397","html":"","typenode":false,"inputs":{"input_1":{"connections":[{"node":"3","input":"output_1"}]}},"outputs":{"output_1":{"connections":[{"node":"9","output":"input_1"}]}},"pos_x":397,"pos_y":-97},"9":{"id":9,"name":"multiple","data":{"question_id":1399},"class":"multiple node-question-1399 node-question-1399 node-question-1399 node-question-1399 node-question-1399 node-question-1399 node-question-1399 node-question-1399","html":"","typenode":false,"inputs":{"input_1":{"connections":[{"node":"7","input":"output_1"},{"node":"3","input":"output_2"}]}},"outputs":{"output_1":{"connections":[{"node":"11","output":"input_1"}]}},"pos_x":626,"pos_y":313},"11":{"id":11,"name":"multiple","data":{"question_id":1401},"class":"multiple node-question-1401 node-question-1401 node-question-1401 node-question-1401 node-question-1401 node-question-1401 node-question-1401 node-question-1401","html":"","typenode":false,"inputs":{"input_1":{"connections":[{"node":"9","input":"output_1"}]}},"outputs":{"output_1":{"connections":[{"node":"12","output":"input_1"}]}},"pos_x":918,"pos_y":181.5},"12":{"id":12,"name":"multiple","data":{"question_id":1402},"class":"multiple node-question-1402 node-question-1402 node-question-1402 node-question-1402 node-question-1402 node-question-1402 node-question-1402 node-question-1402","html":"","typenode":false,"inputs":{"input_1":{"connections":[{"node":"11","input":"output_1"}]}},"outputs":{"output_1":{"connections":[{"node":"13","output":"input_1"}]},"output_2":{"connections":[{"node":"13","output":"input_1"}]},"output_3":{"connections":[{"node":"13","output":"input_1"}]},"output_4":{"connections":[{"node":"13","output":"input_1"}]},"output_5":{"connections":[]}},"pos_x":1165,"pos_y":41.5},"13":{"id":13,"name":"multiple","data":{"question_id":1403},"class":"multiple node-question-1403 node-question-1403 node-question-1403 node-question-1403 node-question-1403 node-question-1403 node-question-1403 node-question-1403","html":"","typenode":false,"inputs":{"input_1":{"connections":[{"node":"12","input":"output_1"},{"node":"12","input":"output_2"},{"node":"12","input":"output_3"},{"node":"12","input":"output_4"}]}},"outputs":{"output_1":{"connections":[{"node":"15","output":"input_1"}]},"output_2":{"connections":[{"node":"15","output":"input_1"}]}},"pos_x":1448,"pos_y":6.9999999999999982236431605997495353221893310546875},"15":{"id":15,"name":"multiple","data":{"question_id":1406},"class":"multiple node-question-1406 node-question-1406 node-question-1406 node-question-1406 node-question-1406 node-question-1406 node-question-1406 node-question-1406","html":"","typenode":false,"inputs":{"input_1":{"connections":[{"node":"13","input":"output_2"},{"node":"13","input":"output_1"}]}},"outputs":{"output_1":{"connections":[]}},"pos_x":1710,"pos_y":114}}}}}',
    'title_name' => 'New Prebuilt',
    'lbb_admin_name' => 'Admin',
    'lbb_chatbot_description' => 'This is description about ADMIN',
    'livechat_status' => 'yes',
    'welcome_message' => '',
    'live_chat_idle_time_enable' => 'yes',
    'how_to_show' => 'minimized',
    'minimized_type' => 'icon',
    'video_text' => 'Talk to live agent',
    'when_to_show' => 'visitor_visit',
    'page_scroll_value' => '10',
    'who_should_see' => 'all_visitor',
    'set_timeout' => '60',
    'email_capture' => 'just_email',
    'lbb_notify_chat' => 'no',
    'chatbot_style_global_status' => '0',
    'lbb_container_width' => '450',
    'lbb_common_font_family' => 'DM Sans,sans-serif',
    'lbb_heading_background_color' => '#2000f0',
    'lbb_image_upload' => 'https://php8.membershipsitechallenge.com/wp-content/plugins/listbuildingbot/admin/images/avatar.png',
    'heading_style_global_status' => '0',
    'lbb_heading_font_size' => '20',
    'lbb_heading_font_weight' => '600',
    'lbb_heading_text_color' => '#fff',
    'lbb_sub_heading_font_size' => '15',
    'lbb_sub_heading_font_weight' => '600',
    'lbb_sub_heading_text_color' => '#ffffff',
    'question_style_global_status' => '0',
    'lbb_question_font_size' => '16',
    'lbb_question_font_weight' => '400',
    'lbb_question_text_color' => '#00000',
    'lbb_question_background_color' => '#ffffff',
    'answer_style_global_status' => '0',
    'lbb_ans_bg_color' => '#0066ff',
    'lbb_ans_border_color' => '#0066ff',
    'lbb_ans_text_color' => '#ffffff',
    'lbb_ans_border_radius' => '5',
    'lbb_ans_font_size' => '16',
    'lbb_ans_font_weight' => '400',
    'alignment_style_global_status' => '0',
    'chat_alignment' => 'right',
    'lbb_right_spacing' => '20',
    'lbb_left_spacing' => '20',
    'lbb_bottom_spacing' => '20',
    'expanded_style_global_status' => '0',
    'backgroun_style_global_status' => '0',
    'lbb_style_chatbot_background' => 'image',
    'lbb_chat_background_color' => '#fff',
    'lbb_chat_background_video' => '',
    'lbb_chat_background_image' => 'http://php8.membershipsitechallenge.com/wp-content/uploads/2019/08/neve-rokophoto-2.png',
    'automation_triggered' => 'after_email',
    'lbb_container_padding' => '15',
    'lbb_question_input_border_color' => '#0066ff',
)
?>